import React, { Component } from "react";
// import "./style.scss";
import "./style.css";
// import './styles.sass';

import { connect } from "react-redux";

import store from "../../store/configureStore";
import { removeNote, changeStatus } from "../../actions/actions";

let arr =
  "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195";
let desc = [
  "The Michael in Damier Graphite canvas is a lightweight backpack combining style and comfort. Ideal for carrying a laptop, books and all essentials, it can be used for business or leisure.",
  "A stylish and easy-to-wear messenger bag, the new District PM is the ideal companion for everyday life. With its elegant details, lightweight and surprisingly spacious interior, it's the perfect combination of functionality and elegance",
  "A stylish and easy-to-wear messenger bag, the new District MM is the ideal companion for everyday life. With its elegant details, lightweight and surprisingly spacious interior, it's the perfect combination of functionality and elegance.",
  "Bringing sophistication to the office, this contemporary briefcase in masculine Eclipse Monogram canvas with distinctive details takes business for pleasure. Enjoy the spacious inside compartments, savour the darker, modern take of our iconic Monogram motif.",
  "Soft faux leather and nylon inner, fashion and durable men shoulder bag.  It features a full front flap with magnetic closure for easy access, an outside front compartment to store small items, a large interior pocket , 2 interior slip pockets ",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown"
];
let titles = [
  "Material  Damier Graphite Canvas",
  "Material Damier Graphite Canvas",
  "Monogram Eclipse Canvas",
  "Briefcase Explorer",
  "Shoulder Bag Business Man Messenger Brown by Alena ",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown",
  "Unknown"
];
let harga = [
  "$2,560.00",
  "$2,350.00",
  "$1,635.00",
  "$2,200.00 ",
  "$20.89",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40",
  "$40"
];

class Cart extends Component {
  constructor(props) {
    super(props);

    this.handleRemove = this.handleRemove.bind(this);
    this.handlePay = this.handlePay.bind(this);
  }
  componentDidMount() {
    document.body.scrollTop = 0;
    document.querySelector(".menu").classList.remove("open");
  }

  

  handleRemove(i) {
    // console.log("asdfasf");
    console.log(i);
    this.props.removeNote(i);
  }
  handlePay(e) {
    e.preventDefault();
    this.props.changeStatus("waiting")
  }

  render() {
    // let ali =
    let total = 0;
    for (let i = 0; i < this.props.notes.length; i++) {
      total +=parseFloat(this.props.notes[i].content.replace("$", "").replace(/,/g, ''))
    }
    if (this.props.notes.length != 0) {
      console.log(this.props.notes[0].url)
    }
    
    return (
      <div className="loginWrapper">
        <h2>Cart</h2>
        <br />
        <div className="cont" style={{ display: "flex" }}>
          {/* <div>
            {img2}
            <h3>{titl2}</h3>
            <h5>{harg2}</h5>
          </div>
          <div>
            {img1}
            <h3>{titl3}</h3>
            <h5>{harg3}</h5>
          </div> */}
          {this.props.notes.map((item, i) => {
            return (
              <div key={i}>
                <img className="image" src={item.url} />
                <h3>{item.title}</h3>
                <h5>{item.content}</h5>
                {/* <button onClick={() => this.props.removeNote(i)}>
                  Remove from cart
                </button> */}
                <button onClick={() => this.handleRemove(i)}>
                  Remove from cart
                </button>
              </div>
            );
          })}
        </div>
        <div>
          <h4>total purchase</h4>
          $ {total}
        </div>
        <div>
          <h2>Payment Method</h2>
          <div style={{display: 'flex'}}>
          <img style={{flex: '1', display: 'block', display: 'flex',
  flexDirection: 'column', maxWidth: '100%', flexFlow: 'row nowrap', alignItems: 'stretch', width: '60px', height: '100%' }} src='https://upload.wikimedia.org/wikipedia/id/8/89/Jenius-logo.png'/>
          <img style={{flex: '1', display: 'block', display: 'flex',
  flexDirection: 'column', maxWidth: '100%', flexFlow: 'row nowrap', alignItems: 'stretch', width: '60px', height: '100%' }} src='https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Debit_Mastercard_logo.svg/1200px-Debit_Mastercard_logo.svg.png'/>
          <img style={{flex: '1', display: 'block', display: 'flex',
  flexDirection: 'column', maxWidth: '100%', flexFlow: 'row nowrap', alignItems: 'stretch', width: '60px', height: '100%' }} src='https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Visa.svg/1200px-Visa.svg.png'/>
          <img style={{flex: '1', display: 'block', display: 'flex',
  flexDirection: 'column', maxWidth: '100%', flexFlow: 'row nowrap', alignItems: 'stretch', width: '60px', height: '100%' }} src='https://statik.tempo.co/data/2019/04/23/id_836405/836405_720.jpg'/>

          </div>
          <a onClick={this.handlePay}>PAY NOW</a>
          
        </div>
      </div>
    );
  }
}

const mapStateToProps = state => {
  return {
    notes: state.notes,
    status: state.status
  };
};

const mapDispatchToProps = {
  removeNote: removeNote,
  changeStatus: changeStatus
};

export default connect(mapStateToProps, mapDispatchToProps)(Cart);
